### ISSUE TITLE
Sign error in `rotate_emis`?

### ISSUE THREAD

**Issue by pkgw** [jadexter/grtrans#9]
I've been working on getting parallel radiative transfer working and I think there might be a sign error in `rotate_emis` in `emis.f90`. The code as written has:

```
e%K(:,5)=c2xi*rhoq-s2xi*rhou
e%K(:,6)=s2xi*rhoq+c2xi*rhou
```

If I work out the alegbra in Shcherbakov & Huang (2011), equations 50 & 51, I find that the sin terms should be negated relative to the above. I get this assuming that the fully general form of the K matrix shown in S&H2011 is:

```
alpha_I alpha_Q alpha_U alpha_V
alpha_Q alpha_I rho_V   rho_U
alpha_U -rho_V  alpha_I rho_Q
alpha_V -rho_U  -rho_Q  alpha_I
```

**Comment by jadexter** [comment]
Hi Peter,

I looked at this a little bit ago and unfortunately think the answer is
that there is a sign error in \rho_U in the general K matrix as shown in
the grtrans paper (and in what you wrote above).

rotate_emis.f90 uses R(\chi) as defined in equations 50 & 51 of
S&H2011 and with this definition after rotation gives what is coded in
rotate_emis.f90. This definition is also consistent with the form of
the rotation matrix in Shcherbakov (2008).

Sorry for the confusion and let me know if you still think there's a problem.

Cheers,
Jason

**Comment by pkgw** [comment]
No worries, this sort of thing is why I asked! If I use the signs shown in Shcherbakov (2008) I reproduce the equations used in `rotate_emis`, so it looks like everything's consistent.
